//
//  CLines.m
//  RTD
//
//  Created by bryce.hammond on 8/10/09.
//  Copyright 2009 Wall Street On Demand, Inc.. All rights reserved.
//

#import "CLine.h"


@implementation CLine

+(NSArray *)newStops
{
	NSMutableArray *returnArray = [[NSMutableArray alloc] init];
	
#pragma mark C Line Northbound Weekday
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//
	//	C Line Northbound Weekday
	//
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	[returnArray addObjectsFromArray:[NSArray arrayWithObjects:
									  [NSArray arrayWithObjects:@"293",@"N",@"Weekday",@"C",@"Evans",@"1",nil],
									  [NSArray arrayWithObjects:@"296",@"N",@"Weekday",@"C",@"I-25/Broadway",@"1",nil],
									  [NSArray arrayWithObjects:@"297",@"N",@"Weekday",@"C",@"Alameda",@"1",nil],
									  [NSArray arrayWithObjects:@"300",@"N",@"Weekday",@"C",@"10th & Osage",@"1",nil],
									  [NSArray arrayWithObjects:@"303",@"N",@"Weekday",@"C",@"Auraria West Campus",@"1",nil],
									  [NSArray arrayWithObjects:@"304",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"1",nil],
									  [NSArray arrayWithObjects:@"306",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"1",nil],
									  [NSArray arrayWithObjects:@"308",@"N",@"Weekday",@"C",@"Union Station",@"1",nil],
									  [NSArray arrayWithObjects:@"323",@"N",@"Weekday",@"C",@"Evans",@"2",nil],
									  [NSArray arrayWithObjects:@"327",@"N",@"Weekday",@"C",@"I-25/Broadway",@"2",nil],
									  [NSArray arrayWithObjects:@"328",@"N",@"Weekday",@"C",@"Alameda",@"2",nil],
									  [NSArray arrayWithObjects:@"332",@"N",@"Weekday",@"C",@"10th & Osage",@"2",nil],
									  [NSArray arrayWithObjects:@"335",@"N",@"Weekday",@"C",@"Auraria West Campus",@"2",nil],
									  [NSArray arrayWithObjects:@"336",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"2",nil],
									  [NSArray arrayWithObjects:@"337",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"2",nil],
									  [NSArray arrayWithObjects:@"339",@"N",@"Weekday",@"C",@"Union Station",@"2",nil],
									  [NSArray arrayWithObjects:@"341",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"3",nil],
									  [NSArray arrayWithObjects:@"344",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"3",nil],
									  [NSArray arrayWithObjects:@"348",@"N",@"Weekday",@"C",@"Oxford",@"3",nil],
									  [NSArray arrayWithObjects:@"350",@"N",@"Weekday",@"C",@"Englewood",@"3",nil],
									  [NSArray arrayWithObjects:@"353",@"N",@"Weekday",@"C",@"Evans",@"3",nil],
									  [NSArray arrayWithObjects:@"356",@"N",@"Weekday",@"C",@"I-25/Broadway",@"3",nil],
									  [NSArray arrayWithObjects:@"358",@"N",@"Weekday",@"C",@"Alameda",@"3",nil],
									  [NSArray arrayWithObjects:@"361",@"N",@"Weekday",@"C",@"10th & Osage",@"3",nil],
									  [NSArray arrayWithObjects:@"364",@"N",@"Weekday",@"C",@"Auraria West Campus",@"3",nil],
									  [NSArray arrayWithObjects:@"365",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"3",nil],
									  [NSArray arrayWithObjects:@"367",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"3",nil],
									  [NSArray arrayWithObjects:@"369",@"N",@"Weekday",@"C",@"Union Station",@"3",nil],
									  [NSArray arrayWithObjects:@"371",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"4",nil],
									  [NSArray arrayWithObjects:@"374",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"4",nil],
									  [NSArray arrayWithObjects:@"378",@"N",@"Weekday",@"C",@"Oxford",@"4",nil],
									  [NSArray arrayWithObjects:@"380",@"N",@"Weekday",@"C",@"Englewood",@"4",nil],
									  [NSArray arrayWithObjects:@"383",@"N",@"Weekday",@"C",@"Evans",@"4",nil],
									  [NSArray arrayWithObjects:@"386",@"N",@"Weekday",@"C",@"I-25/Broadway",@"4",nil],
									  [NSArray arrayWithObjects:@"388",@"N",@"Weekday",@"C",@"Alameda",@"4",nil],
									  [NSArray arrayWithObjects:@"391",@"N",@"Weekday",@"C",@"10th & Osage",@"4",nil],
									  [NSArray arrayWithObjects:@"394",@"N",@"Weekday",@"C",@"Auraria West Campus",@"4",nil],
									  [NSArray arrayWithObjects:@"395",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"4",nil],
									  [NSArray arrayWithObjects:@"397",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"4",nil],
									  [NSArray arrayWithObjects:@"399",@"N",@"Weekday",@"C",@"Union Station",@"4",nil],
									  [NSArray arrayWithObjects:@"401",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"5",nil],
									  [NSArray arrayWithObjects:@"404",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"5",nil],
									  [NSArray arrayWithObjects:@"408",@"N",@"Weekday",@"C",@"Oxford",@"5",nil],
									  [NSArray arrayWithObjects:@"410",@"N",@"Weekday",@"C",@"Englewood",@"5",nil],
									  [NSArray arrayWithObjects:@"413",@"N",@"Weekday",@"C",@"Evans",@"5",nil],
									  [NSArray arrayWithObjects:@"416",@"N",@"Weekday",@"C",@"I-25/Broadway",@"5",nil],
									  [NSArray arrayWithObjects:@"418",@"N",@"Weekday",@"C",@"Alameda",@"5",nil],
									  [NSArray arrayWithObjects:@"421",@"N",@"Weekday",@"C",@"10th & Osage",@"5",nil],
									  [NSArray arrayWithObjects:@"424",@"N",@"Weekday",@"C",@"Auraria West Campus",@"5",nil],
									  [NSArray arrayWithObjects:@"425",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"5",nil],
									  [NSArray arrayWithObjects:@"427",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"5",nil],
									  [NSArray arrayWithObjects:@"429",@"N",@"Weekday",@"C",@"Union Station",@"5",nil],
									  [NSArray arrayWithObjects:@"431",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"6",nil],
									  [NSArray arrayWithObjects:@"434",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"6",nil],
									  [NSArray arrayWithObjects:@"438",@"N",@"Weekday",@"C",@"Oxford",@"6",nil],
									  [NSArray arrayWithObjects:@"440",@"N",@"Weekday",@"C",@"Englewood",@"6",nil],
									  [NSArray arrayWithObjects:@"443",@"N",@"Weekday",@"C",@"Evans",@"6",nil],
									  [NSArray arrayWithObjects:@"446",@"N",@"Weekday",@"C",@"I-25/Broadway",@"6",nil],
									  [NSArray arrayWithObjects:@"448",@"N",@"Weekday",@"C",@"Alameda",@"6",nil],
									  [NSArray arrayWithObjects:@"451",@"N",@"Weekday",@"C",@"10th & Osage",@"6",nil],
									  [NSArray arrayWithObjects:@"454",@"N",@"Weekday",@"C",@"Auraria West Campus",@"6",nil],
									  [NSArray arrayWithObjects:@"455",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"6",nil],
									  [NSArray arrayWithObjects:@"457",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"6",nil],
									  [NSArray arrayWithObjects:@"459",@"N",@"Weekday",@"C",@"Union Station",@"6",nil],
									  [NSArray arrayWithObjects:@"461",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"7",nil],
									  [NSArray arrayWithObjects:@"464",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"7",nil],
									  [NSArray arrayWithObjects:@"468",@"N",@"Weekday",@"C",@"Oxford",@"7",nil],
									  [NSArray arrayWithObjects:@"470",@"N",@"Weekday",@"C",@"Englewood",@"7",nil],
									  [NSArray arrayWithObjects:@"473",@"N",@"Weekday",@"C",@"Evans",@"7",nil],
									  [NSArray arrayWithObjects:@"476",@"N",@"Weekday",@"C",@"I-25/Broadway",@"7",nil],
									  [NSArray arrayWithObjects:@"478",@"N",@"Weekday",@"C",@"Alameda",@"7",nil],
									  [NSArray arrayWithObjects:@"481",@"N",@"Weekday",@"C",@"10th & Osage",@"7",nil],
									  [NSArray arrayWithObjects:@"484",@"N",@"Weekday",@"C",@"Auraria West Campus",@"7",nil],
									  [NSArray arrayWithObjects:@"485",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"7",nil],
									  [NSArray arrayWithObjects:@"487",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"7",nil],
									  [NSArray arrayWithObjects:@"489",@"N",@"Weekday",@"C",@"Union Station",@"7",nil],
									  [NSArray arrayWithObjects:@"491",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"8",nil],
									  [NSArray arrayWithObjects:@"494",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"8",nil],
									  [NSArray arrayWithObjects:@"498",@"N",@"Weekday",@"C",@"Oxford",@"8",nil],
									  [NSArray arrayWithObjects:@"500",@"N",@"Weekday",@"C",@"Englewood",@"8",nil],
									  [NSArray arrayWithObjects:@"503",@"N",@"Weekday",@"C",@"Evans",@"8",nil],
									  [NSArray arrayWithObjects:@"506",@"N",@"Weekday",@"C",@"I-25/Broadway",@"8",nil],
									  [NSArray arrayWithObjects:@"508",@"N",@"Weekday",@"C",@"Alameda",@"8",nil],
									  [NSArray arrayWithObjects:@"511",@"N",@"Weekday",@"C",@"10th & Osage",@"8",nil],
									  [NSArray arrayWithObjects:@"514",@"N",@"Weekday",@"C",@"Auraria West Campus",@"8",nil],
									  [NSArray arrayWithObjects:@"515",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"8",nil],
									  [NSArray arrayWithObjects:@"517",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"8",nil],
									  [NSArray arrayWithObjects:@"519",@"N",@"Weekday",@"C",@"Union Station",@"8",nil],
									  [NSArray arrayWithObjects:@"521",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"9",nil],
									  [NSArray arrayWithObjects:@"524",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"9",nil],
									  [NSArray arrayWithObjects:@"528",@"N",@"Weekday",@"C",@"Oxford",@"9",nil],
									  [NSArray arrayWithObjects:@"530",@"N",@"Weekday",@"C",@"Englewood",@"9",nil],
									  [NSArray arrayWithObjects:@"533",@"N",@"Weekday",@"C",@"Evans",@"9",nil],
									  [NSArray arrayWithObjects:@"536",@"N",@"Weekday",@"C",@"I-25/Broadway",@"9",nil],
									  [NSArray arrayWithObjects:@"538",@"N",@"Weekday",@"C",@"Alameda",@"9",nil],
									  [NSArray arrayWithObjects:@"541",@"N",@"Weekday",@"C",@"10th & Osage",@"9",nil],
									  [NSArray arrayWithObjects:@"544",@"N",@"Weekday",@"C",@"Auraria West Campus",@"9",nil],
									  [NSArray arrayWithObjects:@"545",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"9",nil],
									  [NSArray arrayWithObjects:@"547",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"9",nil],
									  [NSArray arrayWithObjects:@"549",@"N",@"Weekday",@"C",@"Union Station",@"9",nil],
									  [NSArray arrayWithObjects:@"551",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"10",nil],
									  [NSArray arrayWithObjects:@"554",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"10",nil],
									  [NSArray arrayWithObjects:@"558",@"N",@"Weekday",@"C",@"Oxford",@"10",nil],
									  [NSArray arrayWithObjects:@"560",@"N",@"Weekday",@"C",@"Englewood",@"10",nil],
									  [NSArray arrayWithObjects:@"563",@"N",@"Weekday",@"C",@"Evans",@"10",nil],
									  [NSArray arrayWithObjects:@"566",@"N",@"Weekday",@"C",@"I-25/Broadway",@"10",nil],
									  [NSArray arrayWithObjects:@"568",@"N",@"Weekday",@"C",@"Alameda",@"10",nil],
									  [NSArray arrayWithObjects:@"571",@"N",@"Weekday",@"C",@"10th & Osage",@"10",nil],
									  [NSArray arrayWithObjects:@"574",@"N",@"Weekday",@"C",@"Auraria West Campus",@"10",nil],
									  [NSArray arrayWithObjects:@"575",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"10",nil],
									  [NSArray arrayWithObjects:@"577",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"10",nil],
									  [NSArray arrayWithObjects:@"579",@"N",@"Weekday",@"C",@"Union Station",@"10",nil],
									  [NSArray arrayWithObjects:@"596",@"N",@"Weekday",@"C",@"I-25/Broadway",@"11",nil],
									  [NSArray arrayWithObjects:@"598",@"N",@"Weekday",@"C",@"Alameda",@"11",nil],
									  [NSArray arrayWithObjects:@"601",@"N",@"Weekday",@"C",@"10th & Osage",@"11",nil],
									  [NSArray arrayWithObjects:@"604",@"N",@"Weekday",@"C",@"Auraria West Campus",@"11",nil],
									  [NSArray arrayWithObjects:@"605",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"11",nil],
									  [NSArray arrayWithObjects:@"607",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"11",nil],
									  [NSArray arrayWithObjects:@"609",@"N",@"Weekday",@"C",@"Union Station",@"11",nil],
									  [NSArray arrayWithObjects:@"611",@"N",@"Weekday",@"C",@"I-25/Broadway",@"12",nil],
									  [NSArray arrayWithObjects:@"613",@"N",@"Weekday",@"C",@"Alameda",@"12",nil],
									  [NSArray arrayWithObjects:@"616",@"N",@"Weekday",@"C",@"10th & Osage",@"12",nil],
									  [NSArray arrayWithObjects:@"619",@"N",@"Weekday",@"C",@"Auraria West Campus",@"12",nil],
									  [NSArray arrayWithObjects:@"620",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"12",nil],
									  [NSArray arrayWithObjects:@"622",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"12",nil],
									  [NSArray arrayWithObjects:@"624",@"N",@"Weekday",@"C",@"Union Station",@"12",nil],
									  [NSArray arrayWithObjects:@"626",@"N",@"Weekday",@"C",@"I-25/Broadway",@"13",nil],
									  [NSArray arrayWithObjects:@"628",@"N",@"Weekday",@"C",@"Alameda",@"13",nil],
									  [NSArray arrayWithObjects:@"631",@"N",@"Weekday",@"C",@"10th & Osage",@"13",nil],
									  [NSArray arrayWithObjects:@"634",@"N",@"Weekday",@"C",@"Auraria West Campus",@"13",nil],
									  [NSArray arrayWithObjects:@"635",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"13",nil],
									  [NSArray arrayWithObjects:@"637",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"13",nil],
									  [NSArray arrayWithObjects:@"639",@"N",@"Weekday",@"C",@"Union Station",@"13",nil],
									  [NSArray arrayWithObjects:@"641",@"N",@"Weekday",@"C",@"I-25/Broadway",@"14",nil],
									  [NSArray arrayWithObjects:@"643",@"N",@"Weekday",@"C",@"Alameda",@"14",nil],
									  [NSArray arrayWithObjects:@"646",@"N",@"Weekday",@"C",@"10th & Osage",@"14",nil],
									  [NSArray arrayWithObjects:@"649",@"N",@"Weekday",@"C",@"Auraria West Campus",@"14",nil],
									  [NSArray arrayWithObjects:@"650",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"14",nil],
									  [NSArray arrayWithObjects:@"652",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"14",nil],
									  [NSArray arrayWithObjects:@"654",@"N",@"Weekday",@"C",@"Union Station",@"14",nil],
									  [NSArray arrayWithObjects:@"656",@"N",@"Weekday",@"C",@"I-25/Broadway",@"15",nil],
									  [NSArray arrayWithObjects:@"658",@"N",@"Weekday",@"C",@"Alameda",@"15",nil],
									  [NSArray arrayWithObjects:@"661",@"N",@"Weekday",@"C",@"10th & Osage",@"15",nil],
									  [NSArray arrayWithObjects:@"664",@"N",@"Weekday",@"C",@"Auraria West Campus",@"15",nil],
									  [NSArray arrayWithObjects:@"665",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"15",nil],
									  [NSArray arrayWithObjects:@"667",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"15",nil],
									  [NSArray arrayWithObjects:@"669",@"N",@"Weekday",@"C",@"Union Station",@"15",nil],
									  [NSArray arrayWithObjects:@"671",@"N",@"Weekday",@"C",@"I-25/Broadway",@"16",nil],
									  [NSArray arrayWithObjects:@"673",@"N",@"Weekday",@"C",@"Alameda",@"16",nil],
									  [NSArray arrayWithObjects:@"676",@"N",@"Weekday",@"C",@"10th & Osage",@"16",nil],
									  [NSArray arrayWithObjects:@"679",@"N",@"Weekday",@"C",@"Auraria West Campus",@"16",nil],
									  [NSArray arrayWithObjects:@"680",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"16",nil],
									  [NSArray arrayWithObjects:@"682",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"16",nil],
									  [NSArray arrayWithObjects:@"684",@"N",@"Weekday",@"C",@"Union Station",@"16",nil],
									  [NSArray arrayWithObjects:@"686",@"N",@"Weekday",@"C",@"I-25/Broadway",@"17",nil],
									  [NSArray arrayWithObjects:@"688",@"N",@"Weekday",@"C",@"Alameda",@"17",nil],
									  [NSArray arrayWithObjects:@"691",@"N",@"Weekday",@"C",@"10th & Osage",@"17",nil],
									  [NSArray arrayWithObjects:@"694",@"N",@"Weekday",@"C",@"Auraria West Campus",@"17",nil],
									  [NSArray arrayWithObjects:@"695",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"17",nil],
									  [NSArray arrayWithObjects:@"697",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"17",nil],
									  [NSArray arrayWithObjects:@"699",@"N",@"Weekday",@"C",@"Union Station",@"17",nil],
									  [NSArray arrayWithObjects:@"701",@"N",@"Weekday",@"C",@"I-25/Broadway",@"18",nil],
									  [NSArray arrayWithObjects:@"703",@"N",@"Weekday",@"C",@"Alameda",@"18",nil],
									  [NSArray arrayWithObjects:@"706",@"N",@"Weekday",@"C",@"10th & Osage",@"18",nil],
									  [NSArray arrayWithObjects:@"709",@"N",@"Weekday",@"C",@"Auraria West Campus",@"18",nil],
									  [NSArray arrayWithObjects:@"710",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"18",nil],
									  [NSArray arrayWithObjects:@"712",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"18",nil],
									  [NSArray arrayWithObjects:@"714",@"N",@"Weekday",@"C",@"Union Station",@"18",nil],
									  [NSArray arrayWithObjects:@"716",@"N",@"Weekday",@"C",@"I-25/Broadway",@"19",nil],
									  [NSArray arrayWithObjects:@"718",@"N",@"Weekday",@"C",@"Alameda",@"19",nil],
									  [NSArray arrayWithObjects:@"721",@"N",@"Weekday",@"C",@"10th & Osage",@"19",nil],
									  [NSArray arrayWithObjects:@"724",@"N",@"Weekday",@"C",@"Auraria West Campus",@"19",nil],
									  [NSArray arrayWithObjects:@"725",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"19",nil],
									  [NSArray arrayWithObjects:@"727",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"19",nil],
									  [NSArray arrayWithObjects:@"729",@"N",@"Weekday",@"C",@"Union Station",@"19",nil],
									  [NSArray arrayWithObjects:@"731",@"N",@"Weekday",@"C",@"I-25/Broadway",@"20",nil],
									  [NSArray arrayWithObjects:@"733",@"N",@"Weekday",@"C",@"Alameda",@"20",nil],
									  [NSArray arrayWithObjects:@"736",@"N",@"Weekday",@"C",@"10th & Osage",@"20",nil],
									  [NSArray arrayWithObjects:@"739",@"N",@"Weekday",@"C",@"Auraria West Campus",@"20",nil],
									  [NSArray arrayWithObjects:@"740",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"20",nil],
									  [NSArray arrayWithObjects:@"742",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"20",nil],
									  [NSArray arrayWithObjects:@"744",@"N",@"Weekday",@"C",@"Union Station",@"20",nil],
									  [NSArray arrayWithObjects:@"746",@"N",@"Weekday",@"C",@"I-25/Broadway",@"21",nil],
									  [NSArray arrayWithObjects:@"748",@"N",@"Weekday",@"C",@"Alameda",@"21",nil],
									  [NSArray arrayWithObjects:@"751",@"N",@"Weekday",@"C",@"10th & Osage",@"21",nil],
									  [NSArray arrayWithObjects:@"754",@"N",@"Weekday",@"C",@"Auraria West Campus",@"21",nil],
									  [NSArray arrayWithObjects:@"755",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"21",nil],
									  [NSArray arrayWithObjects:@"757",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"21",nil],
									  [NSArray arrayWithObjects:@"759",@"N",@"Weekday",@"C",@"Union Station",@"21",nil],
									  [NSArray arrayWithObjects:@"761",@"N",@"Weekday",@"C",@"I-25/Broadway",@"22",nil],
									  [NSArray arrayWithObjects:@"763",@"N",@"Weekday",@"C",@"Alameda",@"22",nil],
									  [NSArray arrayWithObjects:@"766",@"N",@"Weekday",@"C",@"10th & Osage",@"22",nil],
									  [NSArray arrayWithObjects:@"769",@"N",@"Weekday",@"C",@"Auraria West Campus",@"22",nil],
									  [NSArray arrayWithObjects:@"770",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"22",nil],
									  [NSArray arrayWithObjects:@"772",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"22",nil],
									  [NSArray arrayWithObjects:@"774",@"N",@"Weekday",@"C",@"Union Station",@"22",nil],
									  [NSArray arrayWithObjects:@"776",@"N",@"Weekday",@"C",@"I-25/Broadway",@"23",nil],
									  [NSArray arrayWithObjects:@"778",@"N",@"Weekday",@"C",@"Alameda",@"23",nil],
									  [NSArray arrayWithObjects:@"781",@"N",@"Weekday",@"C",@"10th & Osage",@"23",nil],
									  [NSArray arrayWithObjects:@"784",@"N",@"Weekday",@"C",@"Auraria West Campus",@"23",nil],
									  [NSArray arrayWithObjects:@"785",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"23",nil],
									  [NSArray arrayWithObjects:@"787",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"23",nil],
									  [NSArray arrayWithObjects:@"789",@"N",@"Weekday",@"C",@"Union Station",@"23",nil],
									  [NSArray arrayWithObjects:@"791",@"N",@"Weekday",@"C",@"I-25/Broadway",@"24",nil],
									  [NSArray arrayWithObjects:@"793",@"N",@"Weekday",@"C",@"Alameda",@"24",nil],
									  [NSArray arrayWithObjects:@"796",@"N",@"Weekday",@"C",@"10th & Osage",@"24",nil],
									  [NSArray arrayWithObjects:@"799",@"N",@"Weekday",@"C",@"Auraria West Campus",@"24",nil],
									  [NSArray arrayWithObjects:@"800",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"24",nil],
									  [NSArray arrayWithObjects:@"802",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"24",nil],
									  [NSArray arrayWithObjects:@"804",@"N",@"Weekday",@"C",@"Union Station",@"24",nil],
									  [NSArray arrayWithObjects:@"806",@"N",@"Weekday",@"C",@"I-25/Broadway",@"25",nil],
									  [NSArray arrayWithObjects:@"808",@"N",@"Weekday",@"C",@"Alameda",@"25",nil],
									  [NSArray arrayWithObjects:@"811",@"N",@"Weekday",@"C",@"10th & Osage",@"25",nil],
									  [NSArray arrayWithObjects:@"814",@"N",@"Weekday",@"C",@"Auraria West Campus",@"25",nil],
									  [NSArray arrayWithObjects:@"815",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"25",nil],
									  [NSArray arrayWithObjects:@"817",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"25",nil],
									  [NSArray arrayWithObjects:@"819",@"N",@"Weekday",@"C",@"Union Station",@"25",nil],
									  [NSArray arrayWithObjects:@"821",@"N",@"Weekday",@"C",@"I-25/Broadway",@"26",nil],
									  [NSArray arrayWithObjects:@"823",@"N",@"Weekday",@"C",@"Alameda",@"26",nil],
									  [NSArray arrayWithObjects:@"826",@"N",@"Weekday",@"C",@"10th & Osage",@"26",nil],
									  [NSArray arrayWithObjects:@"829",@"N",@"Weekday",@"C",@"Auraria West Campus",@"26",nil],
									  [NSArray arrayWithObjects:@"830",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"26",nil],
									  [NSArray arrayWithObjects:@"832",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"26",nil],
									  [NSArray arrayWithObjects:@"834",@"N",@"Weekday",@"C",@"Union Station",@"26",nil],
									  [NSArray arrayWithObjects:@"836",@"N",@"Weekday",@"C",@"I-25/Broadway",@"27",nil],
									  [NSArray arrayWithObjects:@"838",@"N",@"Weekday",@"C",@"Alameda",@"27",nil],
									  [NSArray arrayWithObjects:@"841",@"N",@"Weekday",@"C",@"10th & Osage",@"27",nil],
									  [NSArray arrayWithObjects:@"844",@"N",@"Weekday",@"C",@"Auraria West Campus",@"27",nil],
									  [NSArray arrayWithObjects:@"845",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"27",nil],
									  [NSArray arrayWithObjects:@"847",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"27",nil],
									  [NSArray arrayWithObjects:@"849",@"N",@"Weekday",@"C",@"Union Station",@"27",nil],
									  [NSArray arrayWithObjects:@"851",@"N",@"Weekday",@"C",@"I-25/Broadway",@"28",nil],
									  [NSArray arrayWithObjects:@"853",@"N",@"Weekday",@"C",@"Alameda",@"28",nil],
									  [NSArray arrayWithObjects:@"856",@"N",@"Weekday",@"C",@"10th & Osage",@"28",nil],
									  [NSArray arrayWithObjects:@"859",@"N",@"Weekday",@"C",@"Auraria West Campus",@"28",nil],
									  [NSArray arrayWithObjects:@"860",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"28",nil],
									  [NSArray arrayWithObjects:@"862",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"28",nil],
									  [NSArray arrayWithObjects:@"864",@"N",@"Weekday",@"C",@"Union Station",@"28",nil],
									  [NSArray arrayWithObjects:@"863",@"N",@"Weekday",@"C",@"Evans",@"29",nil],
									  [NSArray arrayWithObjects:@"866",@"N",@"Weekday",@"C",@"I-25/Broadway",@"29",nil],
									  [NSArray arrayWithObjects:@"868",@"N",@"Weekday",@"C",@"Alameda",@"29",nil],
									  [NSArray arrayWithObjects:@"871",@"N",@"Weekday",@"C",@"10th & Osage",@"29",nil],
									  [NSArray arrayWithObjects:@"874",@"N",@"Weekday",@"C",@"Auraria West Campus",@"29",nil],
									  [NSArray arrayWithObjects:@"875",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"29",nil],
									  [NSArray arrayWithObjects:@"877",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"29",nil],
									  [NSArray arrayWithObjects:@"879",@"N",@"Weekday",@"C",@"Union Station",@"29",nil],
									  [NSArray arrayWithObjects:@"878",@"N",@"Weekday",@"C",@"Evans",@"30",nil],
									  [NSArray arrayWithObjects:@"881",@"N",@"Weekday",@"C",@"I-25/Broadway",@"30",nil],
									  [NSArray arrayWithObjects:@"883",@"N",@"Weekday",@"C",@"Alameda",@"30",nil],
									  [NSArray arrayWithObjects:@"886",@"N",@"Weekday",@"C",@"10th & Osage",@"30",nil],
									  [NSArray arrayWithObjects:@"889",@"N",@"Weekday",@"C",@"Auraria West Campus",@"30",nil],
									  [NSArray arrayWithObjects:@"890",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"30",nil],
									  [NSArray arrayWithObjects:@"892",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"30",nil],
									  [NSArray arrayWithObjects:@"894",@"N",@"Weekday",@"C",@"Union Station",@"30",nil],
									  [NSArray arrayWithObjects:@"881",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"31",nil],
									  [NSArray arrayWithObjects:@"884",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"31",nil],
									  [NSArray arrayWithObjects:@"888",@"N",@"Weekday",@"C",@"Oxford",@"31",nil],
									  [NSArray arrayWithObjects:@"890",@"N",@"Weekday",@"C",@"Englewood",@"31",nil],
									  [NSArray arrayWithObjects:@"893",@"N",@"Weekday",@"C",@"Evans",@"31",nil],
									  [NSArray arrayWithObjects:@"896",@"N",@"Weekday",@"C",@"I-25/Broadway",@"31",nil],
									  [NSArray arrayWithObjects:@"898",@"N",@"Weekday",@"C",@"Alameda",@"31",nil],
									  [NSArray arrayWithObjects:@"901",@"N",@"Weekday",@"C",@"10th & Osage",@"31",nil],
									  [NSArray arrayWithObjects:@"904",@"N",@"Weekday",@"C",@"Auraria West Campus",@"31",nil],
									  [NSArray arrayWithObjects:@"905",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"31",nil],
									  [NSArray arrayWithObjects:@"907",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"31",nil],
									  [NSArray arrayWithObjects:@"909",@"N",@"Weekday",@"C",@"Union Station",@"31",nil],
									  [NSArray arrayWithObjects:@"908",@"N",@"Weekday",@"C",@"Evans",@"32",nil],
									  [NSArray arrayWithObjects:@"911",@"N",@"Weekday",@"C",@"I-25/Broadway",@"32",nil],
									  [NSArray arrayWithObjects:@"913",@"N",@"Weekday",@"C",@"Alameda",@"32",nil],
									  [NSArray arrayWithObjects:@"916",@"N",@"Weekday",@"C",@"10th & Osage",@"32",nil],
									  [NSArray arrayWithObjects:@"919",@"N",@"Weekday",@"C",@"Auraria West Campus",@"32",nil],
									  [NSArray arrayWithObjects:@"920",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"32",nil],
									  [NSArray arrayWithObjects:@"922",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"32",nil],
									  [NSArray arrayWithObjects:@"924",@"N",@"Weekday",@"C",@"Union Station",@"32",nil],
									  [NSArray arrayWithObjects:@"911",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"33",nil],
									  [NSArray arrayWithObjects:@"914",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"33",nil],
									  [NSArray arrayWithObjects:@"918",@"N",@"Weekday",@"C",@"Oxford",@"33",nil],
									  [NSArray arrayWithObjects:@"920",@"N",@"Weekday",@"C",@"Englewood",@"33",nil],
									  [NSArray arrayWithObjects:@"923",@"N",@"Weekday",@"C",@"Evans",@"33",nil],
									  [NSArray arrayWithObjects:@"926",@"N",@"Weekday",@"C",@"I-25/Broadway",@"33",nil],
									  [NSArray arrayWithObjects:@"928",@"N",@"Weekday",@"C",@"Alameda",@"33",nil],
									  [NSArray arrayWithObjects:@"931",@"N",@"Weekday",@"C",@"10th & Osage",@"33",nil],
									  [NSArray arrayWithObjects:@"934",@"N",@"Weekday",@"C",@"Auraria West Campus",@"33",nil],
									  [NSArray arrayWithObjects:@"935",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"33",nil],
									  [NSArray arrayWithObjects:@"937",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"33",nil],
									  [NSArray arrayWithObjects:@"939",@"N",@"Weekday",@"C",@"Union Station",@"33",nil],
									  [NSArray arrayWithObjects:@"941",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"34",nil],
									  [NSArray arrayWithObjects:@"944",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"34",nil],
									  [NSArray arrayWithObjects:@"948",@"N",@"Weekday",@"C",@"Oxford",@"34",nil],
									  [NSArray arrayWithObjects:@"950",@"N",@"Weekday",@"C",@"Englewood",@"34",nil],
									  [NSArray arrayWithObjects:@"953",@"N",@"Weekday",@"C",@"Evans",@"34",nil],
									  [NSArray arrayWithObjects:@"956",@"N",@"Weekday",@"C",@"I-25/Broadway",@"34",nil],
									  [NSArray arrayWithObjects:@"958",@"N",@"Weekday",@"C",@"Alameda",@"34",nil],
									  [NSArray arrayWithObjects:@"961",@"N",@"Weekday",@"C",@"10th & Osage",@"34",nil],
									  [NSArray arrayWithObjects:@"964",@"N",@"Weekday",@"C",@"Auraria West Campus",@"34",nil],
									  [NSArray arrayWithObjects:@"965",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"34",nil],
									  [NSArray arrayWithObjects:@"967",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"34",nil],
									  [NSArray arrayWithObjects:@"969",@"N",@"Weekday",@"C",@"Union Station",@"34",nil],
									  [NSArray arrayWithObjects:@"971",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"35",nil],
									  [NSArray arrayWithObjects:@"974",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"35",nil],
									  [NSArray arrayWithObjects:@"978",@"N",@"Weekday",@"C",@"Oxford",@"35",nil],
									  [NSArray arrayWithObjects:@"980",@"N",@"Weekday",@"C",@"Englewood",@"35",nil],
									  [NSArray arrayWithObjects:@"983",@"N",@"Weekday",@"C",@"Evans",@"35",nil],
									  [NSArray arrayWithObjects:@"986",@"N",@"Weekday",@"C",@"I-25/Broadway",@"35",nil],
									  [NSArray arrayWithObjects:@"988",@"N",@"Weekday",@"C",@"Alameda",@"35",nil],
									  [NSArray arrayWithObjects:@"991",@"N",@"Weekday",@"C",@"10th & Osage",@"35",nil],
									  [NSArray arrayWithObjects:@"994",@"N",@"Weekday",@"C",@"Auraria West Campus",@"35",nil],
									  [NSArray arrayWithObjects:@"995",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"35",nil],
									  [NSArray arrayWithObjects:@"997",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"35",nil],
									  [NSArray arrayWithObjects:@"999",@"N",@"Weekday",@"C",@"Union Station",@"35",nil],
									  [NSArray arrayWithObjects:@"1001",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"36",nil],
									  [NSArray arrayWithObjects:@"1004",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"36",nil],
									  [NSArray arrayWithObjects:@"1008",@"N",@"Weekday",@"C",@"Oxford",@"36",nil],
									  [NSArray arrayWithObjects:@"1010",@"N",@"Weekday",@"C",@"Englewood",@"36",nil],
									  [NSArray arrayWithObjects:@"1013",@"N",@"Weekday",@"C",@"Evans",@"36",nil],
									  [NSArray arrayWithObjects:@"1016",@"N",@"Weekday",@"C",@"I-25/Broadway",@"36",nil],
									  [NSArray arrayWithObjects:@"1018",@"N",@"Weekday",@"C",@"Alameda",@"36",nil],
									  [NSArray arrayWithObjects:@"1021",@"N",@"Weekday",@"C",@"10th & Osage",@"36",nil],
									  [NSArray arrayWithObjects:@"1024",@"N",@"Weekday",@"C",@"Auraria West Campus",@"36",nil],
									  [NSArray arrayWithObjects:@"1025",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"36",nil],
									  [NSArray arrayWithObjects:@"1027",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"36",nil],
									  [NSArray arrayWithObjects:@"1029",@"N",@"Weekday",@"C",@"Union Station",@"36",nil],
									  [NSArray arrayWithObjects:@"1031",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"37",nil],
									  [NSArray arrayWithObjects:@"1034",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"37",nil],
									  [NSArray arrayWithObjects:@"1038",@"N",@"Weekday",@"C",@"Oxford",@"37",nil],
									  [NSArray arrayWithObjects:@"1040",@"N",@"Weekday",@"C",@"Englewood",@"37",nil],
									  [NSArray arrayWithObjects:@"1043",@"N",@"Weekday",@"C",@"Evans",@"37",nil],
									  [NSArray arrayWithObjects:@"1046",@"N",@"Weekday",@"C",@"I-25/Broadway",@"37",nil],
									  [NSArray arrayWithObjects:@"1048",@"N",@"Weekday",@"C",@"Alameda",@"37",nil],
									  [NSArray arrayWithObjects:@"1051",@"N",@"Weekday",@"C",@"10th & Osage",@"37",nil],
									  [NSArray arrayWithObjects:@"1054",@"N",@"Weekday",@"C",@"Auraria West Campus",@"37",nil],
									  [NSArray arrayWithObjects:@"1055",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"37",nil],
									  [NSArray arrayWithObjects:@"1057",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"37",nil],
									  [NSArray arrayWithObjects:@"1059",@"N",@"Weekday",@"C",@"Union Station",@"37",nil],
									  [NSArray arrayWithObjects:@"1061",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"38",nil],
									  [NSArray arrayWithObjects:@"1064",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"38",nil],
									  [NSArray arrayWithObjects:@"1068",@"N",@"Weekday",@"C",@"Oxford",@"38",nil],
									  [NSArray arrayWithObjects:@"1070",@"N",@"Weekday",@"C",@"Englewood",@"38",nil],
									  [NSArray arrayWithObjects:@"1073",@"N",@"Weekday",@"C",@"Evans",@"38",nil],
									  [NSArray arrayWithObjects:@"1076",@"N",@"Weekday",@"C",@"I-25/Broadway",@"38",nil],
									  [NSArray arrayWithObjects:@"1078",@"N",@"Weekday",@"C",@"Alameda",@"38",nil],
									  [NSArray arrayWithObjects:@"1081",@"N",@"Weekday",@"C",@"10th & Osage",@"38",nil],
									  [NSArray arrayWithObjects:@"1084",@"N",@"Weekday",@"C",@"Auraria West Campus",@"38",nil],
									  [NSArray arrayWithObjects:@"1085",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"38",nil],
									  [NSArray arrayWithObjects:@"1087",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"38",nil],
									  [NSArray arrayWithObjects:@"1089",@"N",@"Weekday",@"C",@"Union Station",@"38",nil],
									  [NSArray arrayWithObjects:@"1091",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"39",nil],
									  [NSArray arrayWithObjects:@"1094",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"39",nil],
									  [NSArray arrayWithObjects:@"1098",@"N",@"Weekday",@"C",@"Oxford",@"39",nil],
									  [NSArray arrayWithObjects:@"1100",@"N",@"Weekday",@"C",@"Englewood",@"39",nil],
									  [NSArray arrayWithObjects:@"1103",@"N",@"Weekday",@"C",@"Evans",@"39",nil],
									  [NSArray arrayWithObjects:@"1106",@"N",@"Weekday",@"C",@"I-25/Broadway",@"39",nil],
									  [NSArray arrayWithObjects:@"1108",@"N",@"Weekday",@"C",@"Alameda",@"39",nil],
									  [NSArray arrayWithObjects:@"1111",@"N",@"Weekday",@"C",@"10th & Osage",@"39",nil],
									  [NSArray arrayWithObjects:@"1114",@"N",@"Weekday",@"C",@"Auraria West Campus",@"39",nil],
									  [NSArray arrayWithObjects:@"1115",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"39",nil],
									  [NSArray arrayWithObjects:@"1117",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"39",nil],
									  [NSArray arrayWithObjects:@"1119",@"N",@"Weekday",@"C",@"Union Station",@"39",nil],
									  [NSArray arrayWithObjects:@"1121",@"N",@"Weekday",@"C",@"Littleton/Mineral",@"40",nil],
									  [NSArray arrayWithObjects:@"1124",@"N",@"Weekday",@"C",@"Littleton/Downtown",@"40",nil],
									  [NSArray arrayWithObjects:@"1128",@"N",@"Weekday",@"C",@"Oxford",@"40",nil],
									  [NSArray arrayWithObjects:@"1130",@"N",@"Weekday",@"C",@"Englewood",@"40",nil],
									  [NSArray arrayWithObjects:@"1133",@"N",@"Weekday",@"C",@"Evans",@"40",nil],
									  [NSArray arrayWithObjects:@"1136",@"N",@"Weekday",@"C",@"I-25/Broadway",@"40",nil],
									  [NSArray arrayWithObjects:@"1138",@"N",@"Weekday",@"C",@"Alameda",@"40",nil],
									  [NSArray arrayWithObjects:@"1141",@"N",@"Weekday",@"C",@"10th & Osage",@"40",nil],
									  [NSArray arrayWithObjects:@"1144",@"N",@"Weekday",@"C",@"Auraria West Campus",@"40",nil],
									  [NSArray arrayWithObjects:@"1145",@"N",@"Weekday",@"C",@"Invesco Field at Mile High",@"40",nil],
									  [NSArray arrayWithObjects:@"1147",@"N",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"40",nil],
									  [NSArray arrayWithObjects:@"1149",@"N",@"Weekday",@"C",@"Union Station",@"40",nil],
									  
								   nil]];
	
#pragma mark C Line Southbound Weekday
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//
	//	C Line Southbound Weekday
	//
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	[returnArray addObjectsFromArray:[NSArray arrayWithObjects:
									  [NSArray arrayWithObjects:@"309",@"S",@"Weekday",@"C",@"Union Station",@"1",nil],
									  [NSArray arrayWithObjects:@"312",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"1",nil],
									  [NSArray arrayWithObjects:@"315",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"1",nil],
									  [NSArray arrayWithObjects:@"317",@"S",@"Weekday",@"C",@"Auraria West Campus",@"1",nil],
									  [NSArray arrayWithObjects:@"320",@"S",@"Weekday",@"C",@"10th & Osage",@"1",nil],
									  [NSArray arrayWithObjects:@"323",@"S",@"Weekday",@"C",@"Alameda",@"1",nil],
									  [NSArray arrayWithObjects:@"325",@"S",@"Weekday",@"C",@"I-25/Broadway",@"1",nil],
									  [NSArray arrayWithObjects:@"328",@"S",@"Weekday",@"C",@"Evans",@"1",nil],
									  [NSArray arrayWithObjects:@"331",@"S",@"Weekday",@"C",@"Englewood",@"1",nil],
									  [NSArray arrayWithObjects:@"333",@"S",@"Weekday",@"C",@"Oxford",@"1",nil],
									  [NSArray arrayWithObjects:@"336",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"1",nil],
									  [NSArray arrayWithObjects:@"339",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"1",nil],
									  [NSArray arrayWithObjects:@"334",@"S",@"Weekday",@"C",@"Union Station",@"2",nil],
									  [NSArray arrayWithObjects:@"337",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"2",nil],
									  [NSArray arrayWithObjects:@"338",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"2",nil],
									  [NSArray arrayWithObjects:@"340",@"S",@"Weekday",@"C",@"Auraria West Campus",@"2",nil],
									  [NSArray arrayWithObjects:@"343",@"S",@"Weekday",@"C",@"10th & Osage",@"2",nil],
									  [NSArray arrayWithObjects:@"346",@"S",@"Weekday",@"C",@"Alameda",@"2",nil],
									  [NSArray arrayWithObjects:@"347",@"S",@"Weekday",@"C",@"I-25/Broadway",@"2",nil],
									  [NSArray arrayWithObjects:@"350",@"S",@"Weekday",@"C",@"Evans",@"2",nil],
									  [NSArray arrayWithObjects:@"353",@"S",@"Weekday",@"C",@"Englewood",@"2",nil],
									  [NSArray arrayWithObjects:@"355",@"S",@"Weekday",@"C",@"Oxford",@"2",nil],
									  [NSArray arrayWithObjects:@"359",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"2",nil],
									  [NSArray arrayWithObjects:@"362",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"2",nil],
									  [NSArray arrayWithObjects:@"362",@"S",@"Weekday",@"C",@"Union Station",@"3",nil],
									  [NSArray arrayWithObjects:@"364",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"3",nil],
									  [NSArray arrayWithObjects:@"366",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"3",nil],
									  [NSArray arrayWithObjects:@"367",@"S",@"Weekday",@"C",@"Auraria West Campus",@"3",nil],
									  [NSArray arrayWithObjects:@"370",@"S",@"Weekday",@"C",@"10th & Osage",@"3",nil],
									  [NSArray arrayWithObjects:@"373",@"S",@"Weekday",@"C",@"Alameda",@"3",nil],
									  [NSArray arrayWithObjects:@"375",@"S",@"Weekday",@"C",@"I-25/Broadway",@"3",nil],
									  [NSArray arrayWithObjects:@"378",@"S",@"Weekday",@"C",@"Evans",@"3",nil],
									  [NSArray arrayWithObjects:@"381",@"S",@"Weekday",@"C",@"Englewood",@"3",nil],
									  [NSArray arrayWithObjects:@"383",@"S",@"Weekday",@"C",@"Oxford",@"3",nil],
									  [NSArray arrayWithObjects:@"386",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"3",nil],
									  [NSArray arrayWithObjects:@"389",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"3",nil],
									  [NSArray arrayWithObjects:@"392",@"S",@"Weekday",@"C",@"Union Station",@"4",nil],
									  [NSArray arrayWithObjects:@"394",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"4",nil],
									  [NSArray arrayWithObjects:@"396",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"4",nil],
									  [NSArray arrayWithObjects:@"397",@"S",@"Weekday",@"C",@"Auraria West Campus",@"4",nil],
									  [NSArray arrayWithObjects:@"400",@"S",@"Weekday",@"C",@"10th & Osage",@"4",nil],
									  [NSArray arrayWithObjects:@"403",@"S",@"Weekday",@"C",@"Alameda",@"4",nil],
									  [NSArray arrayWithObjects:@"405",@"S",@"Weekday",@"C",@"I-25/Broadway",@"4",nil],
									  [NSArray arrayWithObjects:@"408",@"S",@"Weekday",@"C",@"Evans",@"4",nil],
									  [NSArray arrayWithObjects:@"411",@"S",@"Weekday",@"C",@"Englewood",@"4",nil],
									  [NSArray arrayWithObjects:@"413",@"S",@"Weekday",@"C",@"Oxford",@"4",nil],
									  [NSArray arrayWithObjects:@"416",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"4",nil],
									  [NSArray arrayWithObjects:@"419",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"4",nil],
									  [NSArray arrayWithObjects:@"422",@"S",@"Weekday",@"C",@"Union Station",@"5",nil],
									  [NSArray arrayWithObjects:@"424",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"5",nil],
									  [NSArray arrayWithObjects:@"426",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"5",nil],
									  [NSArray arrayWithObjects:@"427",@"S",@"Weekday",@"C",@"Auraria West Campus",@"5",nil],
									  [NSArray arrayWithObjects:@"430",@"S",@"Weekday",@"C",@"10th & Osage",@"5",nil],
									  [NSArray arrayWithObjects:@"433",@"S",@"Weekday",@"C",@"Alameda",@"5",nil],
									  [NSArray arrayWithObjects:@"435",@"S",@"Weekday",@"C",@"I-25/Broadway",@"5",nil],
									  [NSArray arrayWithObjects:@"438",@"S",@"Weekday",@"C",@"Evans",@"5",nil],
									  [NSArray arrayWithObjects:@"441",@"S",@"Weekday",@"C",@"Englewood",@"5",nil],
									  [NSArray arrayWithObjects:@"443",@"S",@"Weekday",@"C",@"Oxford",@"5",nil],
									  [NSArray arrayWithObjects:@"446",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"5",nil],
									  [NSArray arrayWithObjects:@"449",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"5",nil],
									  [NSArray arrayWithObjects:@"452",@"S",@"Weekday",@"C",@"Union Station",@"6",nil],
									  [NSArray arrayWithObjects:@"454",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"6",nil],
									  [NSArray arrayWithObjects:@"456",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"6",nil],
									  [NSArray arrayWithObjects:@"457",@"S",@"Weekday",@"C",@"Auraria West Campus",@"6",nil],
									  [NSArray arrayWithObjects:@"460",@"S",@"Weekday",@"C",@"10th & Osage",@"6",nil],
									  [NSArray arrayWithObjects:@"463",@"S",@"Weekday",@"C",@"Alameda",@"6",nil],
									  [NSArray arrayWithObjects:@"465",@"S",@"Weekday",@"C",@"I-25/Broadway",@"6",nil],
									  [NSArray arrayWithObjects:@"468",@"S",@"Weekday",@"C",@"Evans",@"6",nil],
									  [NSArray arrayWithObjects:@"471",@"S",@"Weekday",@"C",@"Englewood",@"6",nil],
									  [NSArray arrayWithObjects:@"473",@"S",@"Weekday",@"C",@"Oxford",@"6",nil],
									  [NSArray arrayWithObjects:@"476",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"6",nil],
									  [NSArray arrayWithObjects:@"479",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"6",nil],
									  [NSArray arrayWithObjects:@"482",@"S",@"Weekday",@"C",@"Union Station",@"7",nil],
									  [NSArray arrayWithObjects:@"484",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"7",nil],
									  [NSArray arrayWithObjects:@"486",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"7",nil],
									  [NSArray arrayWithObjects:@"487",@"S",@"Weekday",@"C",@"Auraria West Campus",@"7",nil],
									  [NSArray arrayWithObjects:@"490",@"S",@"Weekday",@"C",@"10th & Osage",@"7",nil],
									  [NSArray arrayWithObjects:@"493",@"S",@"Weekday",@"C",@"Alameda",@"7",nil],
									  [NSArray arrayWithObjects:@"495",@"S",@"Weekday",@"C",@"I-25/Broadway",@"7",nil],
									  [NSArray arrayWithObjects:@"498",@"S",@"Weekday",@"C",@"Evans",@"7",nil],
									  [NSArray arrayWithObjects:@"501",@"S",@"Weekday",@"C",@"Englewood",@"7",nil],
									  [NSArray arrayWithObjects:@"503",@"S",@"Weekday",@"C",@"Oxford",@"7",nil],
									  [NSArray arrayWithObjects:@"506",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"7",nil],
									  [NSArray arrayWithObjects:@"509",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"7",nil],
									  [NSArray arrayWithObjects:@"512",@"S",@"Weekday",@"C",@"Union Station",@"8",nil],
									  [NSArray arrayWithObjects:@"514",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"8",nil],
									  [NSArray arrayWithObjects:@"516",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"8",nil],
									  [NSArray arrayWithObjects:@"517",@"S",@"Weekday",@"C",@"Auraria West Campus",@"8",nil],
									  [NSArray arrayWithObjects:@"520",@"S",@"Weekday",@"C",@"10th & Osage",@"8",nil],
									  [NSArray arrayWithObjects:@"523",@"S",@"Weekday",@"C",@"Alameda",@"8",nil],
									  [NSArray arrayWithObjects:@"525",@"S",@"Weekday",@"C",@"I-25/Broadway",@"8",nil],
									  [NSArray arrayWithObjects:@"528",@"S",@"Weekday",@"C",@"Evans",@"8",nil],
									  [NSArray arrayWithObjects:@"531",@"S",@"Weekday",@"C",@"Englewood",@"8",nil],
									  [NSArray arrayWithObjects:@"533",@"S",@"Weekday",@"C",@"Oxford",@"8",nil],
									  [NSArray arrayWithObjects:@"536",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"8",nil],
									  [NSArray arrayWithObjects:@"539",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"8",nil],
									  [NSArray arrayWithObjects:@"527",@"S",@"Weekday",@"C",@"Union Station",@"9",nil],
									  [NSArray arrayWithObjects:@"529",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"9",nil],
									  [NSArray arrayWithObjects:@"531",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"9",nil],
									  [NSArray arrayWithObjects:@"532",@"S",@"Weekday",@"C",@"Auraria West Campus",@"9",nil],
									  [NSArray arrayWithObjects:@"535",@"S",@"Weekday",@"C",@"10th & Osage",@"9",nil],
									  [NSArray arrayWithObjects:@"538",@"S",@"Weekday",@"C",@"Alameda",@"9",nil],
									  [NSArray arrayWithObjects:@"540",@"S",@"Weekday",@"C",@"I-25/Broadway",@"9",nil],
									  [NSArray arrayWithObjects:@"542",@"S",@"Weekday",@"C",@"Union Station",@"10",nil],
									  [NSArray arrayWithObjects:@"544",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"10",nil],
									  [NSArray arrayWithObjects:@"546",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"10",nil],
									  [NSArray arrayWithObjects:@"547",@"S",@"Weekday",@"C",@"Auraria West Campus",@"10",nil],
									  [NSArray arrayWithObjects:@"550",@"S",@"Weekday",@"C",@"10th & Osage",@"10",nil],
									  [NSArray arrayWithObjects:@"553",@"S",@"Weekday",@"C",@"Alameda",@"10",nil],
									  [NSArray arrayWithObjects:@"555",@"S",@"Weekday",@"C",@"I-25/Broadway",@"10",nil],
									  [NSArray arrayWithObjects:@"558",@"S",@"Weekday",@"C",@"Evans",@"10",nil],
									  [NSArray arrayWithObjects:@"561",@"S",@"Weekday",@"C",@"Englewood",@"10",nil],
									  [NSArray arrayWithObjects:@"563",@"S",@"Weekday",@"C",@"Oxford",@"10",nil],
									  [NSArray arrayWithObjects:@"566",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"10",nil],
									  [NSArray arrayWithObjects:@"569",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"10",nil],
									  [NSArray arrayWithObjects:@"557",@"S",@"Weekday",@"C",@"Union Station",@"11",nil],
									  [NSArray arrayWithObjects:@"559",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"11",nil],
									  [NSArray arrayWithObjects:@"561",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"11",nil],
									  [NSArray arrayWithObjects:@"562",@"S",@"Weekday",@"C",@"Auraria West Campus",@"11",nil],
									  [NSArray arrayWithObjects:@"565",@"S",@"Weekday",@"C",@"10th & Osage",@"11",nil],
									  [NSArray arrayWithObjects:@"568",@"S",@"Weekday",@"C",@"Alameda",@"11",nil],
									  [NSArray arrayWithObjects:@"570",@"S",@"Weekday",@"C",@"I-25/Broadway",@"11",nil],
									  [NSArray arrayWithObjects:@"572",@"S",@"Weekday",@"C",@"Union Station",@"12",nil],
									  [NSArray arrayWithObjects:@"574",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"12",nil],
									  [NSArray arrayWithObjects:@"576",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"12",nil],
									  [NSArray arrayWithObjects:@"577",@"S",@"Weekday",@"C",@"Auraria West Campus",@"12",nil],
									  [NSArray arrayWithObjects:@"580",@"S",@"Weekday",@"C",@"10th & Osage",@"12",nil],
									  [NSArray arrayWithObjects:@"583",@"S",@"Weekday",@"C",@"Alameda",@"12",nil],
									  [NSArray arrayWithObjects:@"585",@"S",@"Weekday",@"C",@"I-25/Broadway",@"12",nil],
									  [NSArray arrayWithObjects:@"587",@"S",@"Weekday",@"C",@"Union Station",@"13",nil],
									  [NSArray arrayWithObjects:@"589",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"13",nil],
									  [NSArray arrayWithObjects:@"591",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"13",nil],
									  [NSArray arrayWithObjects:@"592",@"S",@"Weekday",@"C",@"Auraria West Campus",@"13",nil],
									  [NSArray arrayWithObjects:@"595",@"S",@"Weekday",@"C",@"10th & Osage",@"13",nil],
									  [NSArray arrayWithObjects:@"598",@"S",@"Weekday",@"C",@"Alameda",@"13",nil],
									  [NSArray arrayWithObjects:@"600",@"S",@"Weekday",@"C",@"I-25/Broadway",@"13",nil],
									  [NSArray arrayWithObjects:@"602",@"S",@"Weekday",@"C",@"Union Station",@"14",nil],
									  [NSArray arrayWithObjects:@"604",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"14",nil],
									  [NSArray arrayWithObjects:@"606",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"14",nil],
									  [NSArray arrayWithObjects:@"607",@"S",@"Weekday",@"C",@"Auraria West Campus",@"14",nil],
									  [NSArray arrayWithObjects:@"610",@"S",@"Weekday",@"C",@"10th & Osage",@"14",nil],
									  [NSArray arrayWithObjects:@"613",@"S",@"Weekday",@"C",@"Alameda",@"14",nil],
									  [NSArray arrayWithObjects:@"615",@"S",@"Weekday",@"C",@"I-25/Broadway",@"14",nil],
									  [NSArray arrayWithObjects:@"617",@"S",@"Weekday",@"C",@"Union Station",@"15",nil],
									  [NSArray arrayWithObjects:@"619",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"15",nil],
									  [NSArray arrayWithObjects:@"621",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"15",nil],
									  [NSArray arrayWithObjects:@"622",@"S",@"Weekday",@"C",@"Auraria West Campus",@"15",nil],
									  [NSArray arrayWithObjects:@"625",@"S",@"Weekday",@"C",@"10th & Osage",@"15",nil],
									  [NSArray arrayWithObjects:@"628",@"S",@"Weekday",@"C",@"Alameda",@"15",nil],
									  [NSArray arrayWithObjects:@"630",@"S",@"Weekday",@"C",@"I-25/Broadway",@"15",nil],
									  [NSArray arrayWithObjects:@"632",@"S",@"Weekday",@"C",@"Union Station",@"16",nil],
									  [NSArray arrayWithObjects:@"634",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"16",nil],
									  [NSArray arrayWithObjects:@"636",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"16",nil],
									  [NSArray arrayWithObjects:@"637",@"S",@"Weekday",@"C",@"Auraria West Campus",@"16",nil],
									  [NSArray arrayWithObjects:@"640",@"S",@"Weekday",@"C",@"10th & Osage",@"16",nil],
									  [NSArray arrayWithObjects:@"643",@"S",@"Weekday",@"C",@"Alameda",@"16",nil],
									  [NSArray arrayWithObjects:@"645",@"S",@"Weekday",@"C",@"I-25/Broadway",@"16",nil],
									  [NSArray arrayWithObjects:@"647",@"S",@"Weekday",@"C",@"Union Station",@"17",nil],
									  [NSArray arrayWithObjects:@"649",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"17",nil],
									  [NSArray arrayWithObjects:@"651",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"17",nil],
									  [NSArray arrayWithObjects:@"652",@"S",@"Weekday",@"C",@"Auraria West Campus",@"17",nil],
									  [NSArray arrayWithObjects:@"655",@"S",@"Weekday",@"C",@"10th & Osage",@"17",nil],
									  [NSArray arrayWithObjects:@"658",@"S",@"Weekday",@"C",@"Alameda",@"17",nil],
									  [NSArray arrayWithObjects:@"660",@"S",@"Weekday",@"C",@"I-25/Broadway",@"17",nil],
									  [NSArray arrayWithObjects:@"662",@"S",@"Weekday",@"C",@"Union Station",@"18",nil],
									  [NSArray arrayWithObjects:@"664",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"18",nil],
									  [NSArray arrayWithObjects:@"666",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"18",nil],
									  [NSArray arrayWithObjects:@"667",@"S",@"Weekday",@"C",@"Auraria West Campus",@"18",nil],
									  [NSArray arrayWithObjects:@"670",@"S",@"Weekday",@"C",@"10th & Osage",@"18",nil],
									  [NSArray arrayWithObjects:@"673",@"S",@"Weekday",@"C",@"Alameda",@"18",nil],
									  [NSArray arrayWithObjects:@"675",@"S",@"Weekday",@"C",@"I-25/Broadway",@"18",nil],
									  [NSArray arrayWithObjects:@"677",@"S",@"Weekday",@"C",@"Union Station",@"19",nil],
									  [NSArray arrayWithObjects:@"679",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"19",nil],
									  [NSArray arrayWithObjects:@"681",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"19",nil],
									  [NSArray arrayWithObjects:@"682",@"S",@"Weekday",@"C",@"Auraria West Campus",@"19",nil],
									  [NSArray arrayWithObjects:@"685",@"S",@"Weekday",@"C",@"10th & Osage",@"19",nil],
									  [NSArray arrayWithObjects:@"688",@"S",@"Weekday",@"C",@"Alameda",@"19",nil],
									  [NSArray arrayWithObjects:@"690",@"S",@"Weekday",@"C",@"I-25/Broadway",@"19",nil],
									  [NSArray arrayWithObjects:@"692",@"S",@"Weekday",@"C",@"Union Station",@"20",nil],
									  [NSArray arrayWithObjects:@"694",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"20",nil],
									  [NSArray arrayWithObjects:@"696",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"20",nil],
									  [NSArray arrayWithObjects:@"697",@"S",@"Weekday",@"C",@"Auraria West Campus",@"20",nil],
									  [NSArray arrayWithObjects:@"700",@"S",@"Weekday",@"C",@"10th & Osage",@"20",nil],
									  [NSArray arrayWithObjects:@"703",@"S",@"Weekday",@"C",@"Alameda",@"20",nil],
									  [NSArray arrayWithObjects:@"705",@"S",@"Weekday",@"C",@"I-25/Broadway",@"20",nil],
									  [NSArray arrayWithObjects:@"707",@"S",@"Weekday",@"C",@"Union Station",@"21",nil],
									  [NSArray arrayWithObjects:@"709",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"21",nil],
									  [NSArray arrayWithObjects:@"711",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"21",nil],
									  [NSArray arrayWithObjects:@"712",@"S",@"Weekday",@"C",@"Auraria West Campus",@"21",nil],
									  [NSArray arrayWithObjects:@"715",@"S",@"Weekday",@"C",@"10th & Osage",@"21",nil],
									  [NSArray arrayWithObjects:@"718",@"S",@"Weekday",@"C",@"Alameda",@"21",nil],
									  [NSArray arrayWithObjects:@"720",@"S",@"Weekday",@"C",@"I-25/Broadway",@"21",nil],
									  [NSArray arrayWithObjects:@"722",@"S",@"Weekday",@"C",@"Union Station",@"22",nil],
									  [NSArray arrayWithObjects:@"724",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"22",nil],
									  [NSArray arrayWithObjects:@"726",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"22",nil],
									  [NSArray arrayWithObjects:@"727",@"S",@"Weekday",@"C",@"Auraria West Campus",@"22",nil],
									  [NSArray arrayWithObjects:@"730",@"S",@"Weekday",@"C",@"10th & Osage",@"22",nil],
									  [NSArray arrayWithObjects:@"733",@"S",@"Weekday",@"C",@"Alameda",@"22",nil],
									  [NSArray arrayWithObjects:@"735",@"S",@"Weekday",@"C",@"I-25/Broadway",@"22",nil],
									  [NSArray arrayWithObjects:@"737",@"S",@"Weekday",@"C",@"Union Station",@"23",nil],
									  [NSArray arrayWithObjects:@"739",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"23",nil],
									  [NSArray arrayWithObjects:@"741",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"23",nil],
									  [NSArray arrayWithObjects:@"742",@"S",@"Weekday",@"C",@"Auraria West Campus",@"23",nil],
									  [NSArray arrayWithObjects:@"745",@"S",@"Weekday",@"C",@"10th & Osage",@"23",nil],
									  [NSArray arrayWithObjects:@"748",@"S",@"Weekday",@"C",@"Alameda",@"23",nil],
									  [NSArray arrayWithObjects:@"750",@"S",@"Weekday",@"C",@"I-25/Broadway",@"23",nil],
									  [NSArray arrayWithObjects:@"752",@"S",@"Weekday",@"C",@"Union Station",@"24",nil],
									  [NSArray arrayWithObjects:@"754",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"24",nil],
									  [NSArray arrayWithObjects:@"756",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"24",nil],
									  [NSArray arrayWithObjects:@"757",@"S",@"Weekday",@"C",@"Auraria West Campus",@"24",nil],
									  [NSArray arrayWithObjects:@"760",@"S",@"Weekday",@"C",@"10th & Osage",@"24",nil],
									  [NSArray arrayWithObjects:@"763",@"S",@"Weekday",@"C",@"Alameda",@"24",nil],
									  [NSArray arrayWithObjects:@"765",@"S",@"Weekday",@"C",@"I-25/Broadway",@"24",nil],
									  [NSArray arrayWithObjects:@"767",@"S",@"Weekday",@"C",@"Union Station",@"25",nil],
									  [NSArray arrayWithObjects:@"769",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"25",nil],
									  [NSArray arrayWithObjects:@"771",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"25",nil],
									  [NSArray arrayWithObjects:@"772",@"S",@"Weekday",@"C",@"Auraria West Campus",@"25",nil],
									  [NSArray arrayWithObjects:@"775",@"S",@"Weekday",@"C",@"10th & Osage",@"25",nil],
									  [NSArray arrayWithObjects:@"778",@"S",@"Weekday",@"C",@"Alameda",@"25",nil],
									  [NSArray arrayWithObjects:@"780",@"S",@"Weekday",@"C",@"I-25/Broadway",@"25",nil],
									  [NSArray arrayWithObjects:@"782",@"S",@"Weekday",@"C",@"Union Station",@"26",nil],
									  [NSArray arrayWithObjects:@"784",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"26",nil],
									  [NSArray arrayWithObjects:@"786",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"26",nil],
									  [NSArray arrayWithObjects:@"787",@"S",@"Weekday",@"C",@"Auraria West Campus",@"26",nil],
									  [NSArray arrayWithObjects:@"790",@"S",@"Weekday",@"C",@"10th & Osage",@"26",nil],
									  [NSArray arrayWithObjects:@"793",@"S",@"Weekday",@"C",@"Alameda",@"26",nil],
									  [NSArray arrayWithObjects:@"795",@"S",@"Weekday",@"C",@"I-25/Broadway",@"26",nil],
									  [NSArray arrayWithObjects:@"797",@"S",@"Weekday",@"C",@"Union Station",@"27",nil],
									  [NSArray arrayWithObjects:@"799",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"27",nil],
									  [NSArray arrayWithObjects:@"801",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"27",nil],
									  [NSArray arrayWithObjects:@"802",@"S",@"Weekday",@"C",@"Auraria West Campus",@"27",nil],
									  [NSArray arrayWithObjects:@"805",@"S",@"Weekday",@"C",@"10th & Osage",@"27",nil],
									  [NSArray arrayWithObjects:@"808",@"S",@"Weekday",@"C",@"Alameda",@"27",nil],
									  [NSArray arrayWithObjects:@"810",@"S",@"Weekday",@"C",@"I-25/Broadway",@"27",nil],
									  [NSArray arrayWithObjects:@"812",@"S",@"Weekday",@"C",@"Union Station",@"28",nil],
									  [NSArray arrayWithObjects:@"814",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"28",nil],
									  [NSArray arrayWithObjects:@"816",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"28",nil],
									  [NSArray arrayWithObjects:@"817",@"S",@"Weekday",@"C",@"Auraria West Campus",@"28",nil],
									  [NSArray arrayWithObjects:@"820",@"S",@"Weekday",@"C",@"10th & Osage",@"28",nil],
									  [NSArray arrayWithObjects:@"823",@"S",@"Weekday",@"C",@"Alameda",@"28",nil],
									  [NSArray arrayWithObjects:@"825",@"S",@"Weekday",@"C",@"I-25/Broadway",@"28",nil],
									  [NSArray arrayWithObjects:@"827",@"S",@"Weekday",@"C",@"Union Station",@"29",nil],
									  [NSArray arrayWithObjects:@"829",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"29",nil],
									  [NSArray arrayWithObjects:@"831",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"29",nil],
									  [NSArray arrayWithObjects:@"832",@"S",@"Weekday",@"C",@"Auraria West Campus",@"29",nil],
									  [NSArray arrayWithObjects:@"835",@"S",@"Weekday",@"C",@"10th & Osage",@"29",nil],
									  [NSArray arrayWithObjects:@"838",@"S",@"Weekday",@"C",@"Alameda",@"29",nil],
									  [NSArray arrayWithObjects:@"840",@"S",@"Weekday",@"C",@"I-25/Broadway",@"29",nil],
									  [NSArray arrayWithObjects:@"842",@"S",@"Weekday",@"C",@"Union Station",@"30",nil],
									  [NSArray arrayWithObjects:@"844",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"30",nil],
									  [NSArray arrayWithObjects:@"846",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"30",nil],
									  [NSArray arrayWithObjects:@"847",@"S",@"Weekday",@"C",@"Auraria West Campus",@"30",nil],
									  [NSArray arrayWithObjects:@"850",@"S",@"Weekday",@"C",@"10th & Osage",@"30",nil],
									  [NSArray arrayWithObjects:@"853",@"S",@"Weekday",@"C",@"Alameda",@"30",nil],
									  [NSArray arrayWithObjects:@"855",@"S",@"Weekday",@"C",@"I-25/Broadway",@"30",nil],
									  [NSArray arrayWithObjects:@"858",@"S",@"Weekday",@"C",@"Evans",@"30",nil],
									  [NSArray arrayWithObjects:@"861",@"S",@"Weekday",@"C",@"Englewood",@"30",nil],
									  [NSArray arrayWithObjects:@"863",@"S",@"Weekday",@"C",@"Oxford",@"30",nil],
									  [NSArray arrayWithObjects:@"866",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"30",nil],
									  [NSArray arrayWithObjects:@"870",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"30",nil],
									  [NSArray arrayWithObjects:@"872",@"S",@"Weekday",@"C",@"Union Station",@"31",nil],
									  [NSArray arrayWithObjects:@"874",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"31",nil],
									  [NSArray arrayWithObjects:@"876",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"31",nil],
									  [NSArray arrayWithObjects:@"877",@"S",@"Weekday",@"C",@"Auraria West Campus",@"31",nil],
									  [NSArray arrayWithObjects:@"880",@"S",@"Weekday",@"C",@"10th & Osage",@"31",nil],
									  [NSArray arrayWithObjects:@"883",@"S",@"Weekday",@"C",@"Alameda",@"31",nil],
									  [NSArray arrayWithObjects:@"885",@"S",@"Weekday",@"C",@"I-25/Broadway",@"31",nil],
									  [NSArray arrayWithObjects:@"888",@"S",@"Weekday",@"C",@"Evans",@"31",nil],
									  [NSArray arrayWithObjects:@"891",@"S",@"Weekday",@"C",@"Englewood",@"31",nil],
									  [NSArray arrayWithObjects:@"893",@"S",@"Weekday",@"C",@"Oxford",@"31",nil],
									  [NSArray arrayWithObjects:@"896",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"31",nil],
									  [NSArray arrayWithObjects:@"900",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"31",nil],
									  [NSArray arrayWithObjects:@"902",@"S",@"Weekday",@"C",@"Union Station",@"32",nil],
									  [NSArray arrayWithObjects:@"905",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"32",nil],
									  [NSArray arrayWithObjects:@"906",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"32",nil],
									  [NSArray arrayWithObjects:@"908",@"S",@"Weekday",@"C",@"Auraria West Campus",@"32",nil],
									  [NSArray arrayWithObjects:@"911",@"S",@"Weekday",@"C",@"10th & Osage",@"32",nil],
									  [NSArray arrayWithObjects:@"914",@"S",@"Weekday",@"C",@"Alameda",@"32",nil],
									  [NSArray arrayWithObjects:@"915",@"S",@"Weekday",@"C",@"I-25/Broadway",@"32",nil],
									  [NSArray arrayWithObjects:@"918",@"S",@"Weekday",@"C",@"Evans",@"32",nil],
									  [NSArray arrayWithObjects:@"921",@"S",@"Weekday",@"C",@"Englewood",@"32",nil],
									  [NSArray arrayWithObjects:@"923",@"S",@"Weekday",@"C",@"Oxford",@"32",nil],
									  [NSArray arrayWithObjects:@"927",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"32",nil],
									  [NSArray arrayWithObjects:@"930",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"32",nil],
									  [NSArray arrayWithObjects:@"932",@"S",@"Weekday",@"C",@"Union Station",@"33",nil],
									  [NSArray arrayWithObjects:@"935",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"33",nil],
									  [NSArray arrayWithObjects:@"936",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"33",nil],
									  [NSArray arrayWithObjects:@"938",@"S",@"Weekday",@"C",@"Auraria West Campus",@"33",nil],
									  [NSArray arrayWithObjects:@"941",@"S",@"Weekday",@"C",@"10th & Osage",@"33",nil],
									  [NSArray arrayWithObjects:@"944",@"S",@"Weekday",@"C",@"Alameda",@"33",nil],
									  [NSArray arrayWithObjects:@"945",@"S",@"Weekday",@"C",@"I-25/Broadway",@"33",nil],
									  [NSArray arrayWithObjects:@"948",@"S",@"Weekday",@"C",@"Evans",@"33",nil],
									  [NSArray arrayWithObjects:@"951",@"S",@"Weekday",@"C",@"Englewood",@"33",nil],
									  [NSArray arrayWithObjects:@"953",@"S",@"Weekday",@"C",@"Oxford",@"33",nil],
									  [NSArray arrayWithObjects:@"957",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"33",nil],
									  [NSArray arrayWithObjects:@"960",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"33",nil],
									  [NSArray arrayWithObjects:@"962",@"S",@"Weekday",@"C",@"Union Station",@"34",nil],
									  [NSArray arrayWithObjects:@"965",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"34",nil],
									  [NSArray arrayWithObjects:@"966",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"34",nil],
									  [NSArray arrayWithObjects:@"968",@"S",@"Weekday",@"C",@"Auraria West Campus",@"34",nil],
									  [NSArray arrayWithObjects:@"971",@"S",@"Weekday",@"C",@"10th & Osage",@"34",nil],
									  [NSArray arrayWithObjects:@"974",@"S",@"Weekday",@"C",@"Alameda",@"34",nil],
									  [NSArray arrayWithObjects:@"975",@"S",@"Weekday",@"C",@"I-25/Broadway",@"34",nil],
									  [NSArray arrayWithObjects:@"978",@"S",@"Weekday",@"C",@"Evans",@"34",nil],
									  [NSArray arrayWithObjects:@"981",@"S",@"Weekday",@"C",@"Englewood",@"34",nil],
									  [NSArray arrayWithObjects:@"983",@"S",@"Weekday",@"C",@"Oxford",@"34",nil],
									  [NSArray arrayWithObjects:@"987",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"34",nil],
									  [NSArray arrayWithObjects:@"990",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"34",nil],
									  [NSArray arrayWithObjects:@"992",@"S",@"Weekday",@"C",@"Union Station",@"35",nil],
									  [NSArray arrayWithObjects:@"995",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"35",nil],
									  [NSArray arrayWithObjects:@"996",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"35",nil],
									  [NSArray arrayWithObjects:@"998",@"S",@"Weekday",@"C",@"Auraria West Campus",@"35",nil],
									  [NSArray arrayWithObjects:@"1001",@"S",@"Weekday",@"C",@"10th & Osage",@"35",nil],
									  [NSArray arrayWithObjects:@"1004",@"S",@"Weekday",@"C",@"Alameda",@"35",nil],
									  [NSArray arrayWithObjects:@"1005",@"S",@"Weekday",@"C",@"I-25/Broadway",@"35",nil],
									  [NSArray arrayWithObjects:@"1008",@"S",@"Weekday",@"C",@"Evans",@"35",nil],
									  [NSArray arrayWithObjects:@"1011",@"S",@"Weekday",@"C",@"Englewood",@"35",nil],
									  [NSArray arrayWithObjects:@"1013",@"S",@"Weekday",@"C",@"Oxford",@"35",nil],
									  [NSArray arrayWithObjects:@"1017",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"35",nil],
									  [NSArray arrayWithObjects:@"1020",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"35",nil],
									  [NSArray arrayWithObjects:@"1022",@"S",@"Weekday",@"C",@"Union Station",@"36",nil],
									  [NSArray arrayWithObjects:@"1025",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"36",nil],
									  [NSArray arrayWithObjects:@"1026",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"36",nil],
									  [NSArray arrayWithObjects:@"1028",@"S",@"Weekday",@"C",@"Auraria West Campus",@"36",nil],
									  [NSArray arrayWithObjects:@"1031",@"S",@"Weekday",@"C",@"10th & Osage",@"36",nil],
									  [NSArray arrayWithObjects:@"1034",@"S",@"Weekday",@"C",@"Alameda",@"36",nil],
									  [NSArray arrayWithObjects:@"1035",@"S",@"Weekday",@"C",@"I-25/Broadway",@"36",nil],
									  [NSArray arrayWithObjects:@"1038",@"S",@"Weekday",@"C",@"Evans",@"36",nil],
									  [NSArray arrayWithObjects:@"1041",@"S",@"Weekday",@"C",@"Englewood",@"36",nil],
									  [NSArray arrayWithObjects:@"1043",@"S",@"Weekday",@"C",@"Oxford",@"36",nil],
									  [NSArray arrayWithObjects:@"1047",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"36",nil],
									  [NSArray arrayWithObjects:@"1050",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"36",nil],
									  [NSArray arrayWithObjects:@"1052",@"S",@"Weekday",@"C",@"Union Station",@"37",nil],
									  [NSArray arrayWithObjects:@"1055",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"37",nil],
									  [NSArray arrayWithObjects:@"1056",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"37",nil],
									  [NSArray arrayWithObjects:@"1058",@"S",@"Weekday",@"C",@"Auraria West Campus",@"37",nil],
									  [NSArray arrayWithObjects:@"1061",@"S",@"Weekday",@"C",@"10th & Osage",@"37",nil],
									  [NSArray arrayWithObjects:@"1064",@"S",@"Weekday",@"C",@"Alameda",@"37",nil],
									  [NSArray arrayWithObjects:@"1065",@"S",@"Weekday",@"C",@"I-25/Broadway",@"37",nil],
									  [NSArray arrayWithObjects:@"1068",@"S",@"Weekday",@"C",@"Evans",@"37",nil],
									  [NSArray arrayWithObjects:@"1071",@"S",@"Weekday",@"C",@"Englewood",@"37",nil],
									  [NSArray arrayWithObjects:@"1073",@"S",@"Weekday",@"C",@"Oxford",@"37",nil],
									  [NSArray arrayWithObjects:@"1077",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"37",nil],
									  [NSArray arrayWithObjects:@"1080",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"37",nil],
									  [NSArray arrayWithObjects:@"1082",@"S",@"Weekday",@"C",@"Union Station",@"38",nil],
									  [NSArray arrayWithObjects:@"1085",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"38",nil],
									  [NSArray arrayWithObjects:@"1086",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"38",nil],
									  [NSArray arrayWithObjects:@"1088",@"S",@"Weekday",@"C",@"Auraria West Campus",@"38",nil],
									  [NSArray arrayWithObjects:@"1091",@"S",@"Weekday",@"C",@"10th & Osage",@"38",nil],
									  [NSArray arrayWithObjects:@"1094",@"S",@"Weekday",@"C",@"Alameda",@"38",nil],
									  [NSArray arrayWithObjects:@"1095",@"S",@"Weekday",@"C",@"I-25/Broadway",@"38",nil],
									  [NSArray arrayWithObjects:@"1098",@"S",@"Weekday",@"C",@"Evans",@"38",nil],
									  [NSArray arrayWithObjects:@"1101",@"S",@"Weekday",@"C",@"Englewood",@"38",nil],
									  [NSArray arrayWithObjects:@"1103",@"S",@"Weekday",@"C",@"Oxford",@"38",nil],
									  [NSArray arrayWithObjects:@"1107",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"38",nil],
									  [NSArray arrayWithObjects:@"1110",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"38",nil],
									  [NSArray arrayWithObjects:@"1111",@"S",@"Weekday",@"C",@"Union Station",@"39",nil],
									  [NSArray arrayWithObjects:@"1114",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"39",nil],
									  [NSArray arrayWithObjects:@"1115",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"39",nil],
									  [NSArray arrayWithObjects:@"1117",@"S",@"Weekday",@"C",@"Auraria West Campus",@"39",nil],
									  [NSArray arrayWithObjects:@"1120",@"S",@"Weekday",@"C",@"10th & Osage",@"39",nil],
									  [NSArray arrayWithObjects:@"1123",@"S",@"Weekday",@"C",@"Alameda",@"39",nil],
									  [NSArray arrayWithObjects:@"1124",@"S",@"Weekday",@"C",@"I-25/Broadway",@"39",nil],
									  [NSArray arrayWithObjects:@"1127",@"S",@"Weekday",@"C",@"Evans",@"39",nil],
									  [NSArray arrayWithObjects:@"1130",@"S",@"Weekday",@"C",@"Englewood",@"39",nil],
									  [NSArray arrayWithObjects:@"1132",@"S",@"Weekday",@"C",@"Oxford",@"39",nil],
									  [NSArray arrayWithObjects:@"1136",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"39",nil],
									  [NSArray arrayWithObjects:@"1139",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"39",nil],
									  [NSArray arrayWithObjects:@"1141",@"S",@"Weekday",@"C",@"Union Station",@"40",nil],
									  [NSArray arrayWithObjects:@"1144",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"40",nil],
									  [NSArray arrayWithObjects:@"1145",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"40",nil],
									  [NSArray arrayWithObjects:@"1147",@"S",@"Weekday",@"C",@"Auraria West Campus",@"40",nil],
									  [NSArray arrayWithObjects:@"1150",@"S",@"Weekday",@"C",@"10th & Osage",@"40",nil],
									  [NSArray arrayWithObjects:@"1153",@"S",@"Weekday",@"C",@"Alameda",@"40",nil],
									  [NSArray arrayWithObjects:@"1154",@"S",@"Weekday",@"C",@"I-25/Broadway",@"40",nil],
									  [NSArray arrayWithObjects:@"1157",@"S",@"Weekday",@"C",@"Evans",@"40",nil],
									  [NSArray arrayWithObjects:@"1160",@"S",@"Weekday",@"C",@"Englewood",@"40",nil],
									  [NSArray arrayWithObjects:@"1162",@"S",@"Weekday",@"C",@"Oxford",@"40",nil],
									  [NSArray arrayWithObjects:@"1166",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"40",nil],
									  [NSArray arrayWithObjects:@"1169",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"40",nil],
									  [NSArray arrayWithObjects:@"1171",@"S",@"Weekday",@"C",@"Union Station",@"41",nil],
									  [NSArray arrayWithObjects:@"1174",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"41",nil],
									  [NSArray arrayWithObjects:@"1175",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"41",nil],
									  [NSArray arrayWithObjects:@"1177",@"S",@"Weekday",@"C",@"Auraria West Campus",@"41",nil],
									  [NSArray arrayWithObjects:@"1180",@"S",@"Weekday",@"C",@"10th & Osage",@"41",nil],
									  [NSArray arrayWithObjects:@"1183",@"S",@"Weekday",@"C",@"Alameda",@"41",nil],
									  [NSArray arrayWithObjects:@"1184",@"S",@"Weekday",@"C",@"I-25/Broadway",@"41",nil],
									  [NSArray arrayWithObjects:@"1187",@"S",@"Weekday",@"C",@"Evans",@"41",nil],
									  [NSArray arrayWithObjects:@"1190",@"S",@"Weekday",@"C",@"Englewood",@"41",nil],
									  [NSArray arrayWithObjects:@"1192",@"S",@"Weekday",@"C",@"Oxford",@"41",nil],
									  [NSArray arrayWithObjects:@"1196",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"41",nil],
									  [NSArray arrayWithObjects:@"1199",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"41",nil],
									  [NSArray arrayWithObjects:@"1201",@"S",@"Weekday",@"C",@"Union Station",@"42",nil],
									  [NSArray arrayWithObjects:@"1204",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"42",nil],
									  [NSArray arrayWithObjects:@"1205",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"42",nil],
									  [NSArray arrayWithObjects:@"1207",@"S",@"Weekday",@"C",@"Auraria West Campus",@"42",nil],
									  [NSArray arrayWithObjects:@"1210",@"S",@"Weekday",@"C",@"10th & Osage",@"42",nil],
									  [NSArray arrayWithObjects:@"1213",@"S",@"Weekday",@"C",@"Alameda",@"42",nil],
									  [NSArray arrayWithObjects:@"1214",@"S",@"Weekday",@"C",@"I-25/Broadway",@"42",nil],
									  [NSArray arrayWithObjects:@"1217",@"S",@"Weekday",@"C",@"Evans",@"42",nil],
									  [NSArray arrayWithObjects:@"1220",@"S",@"Weekday",@"C",@"Englewood",@"42",nil],
									  [NSArray arrayWithObjects:@"1222",@"S",@"Weekday",@"C",@"Oxford",@"42",nil],
									  [NSArray arrayWithObjects:@"1226",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"42",nil],
									  [NSArray arrayWithObjects:@"1229",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"42",nil],
									  [NSArray arrayWithObjects:@"1231",@"S",@"Weekday",@"C",@"Union Station",@"43",nil],
									  [NSArray arrayWithObjects:@"1234",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"43",nil],
									  [NSArray arrayWithObjects:@"1235",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"43",nil],
									  [NSArray arrayWithObjects:@"1237",@"S",@"Weekday",@"C",@"Auraria West Campus",@"43",nil],
									  [NSArray arrayWithObjects:@"1240",@"S",@"Weekday",@"C",@"10th & Osage",@"43",nil],
									  [NSArray arrayWithObjects:@"1243",@"S",@"Weekday",@"C",@"Alameda",@"43",nil],
									  [NSArray arrayWithObjects:@"1244",@"S",@"Weekday",@"C",@"I-25/Broadway",@"43",nil],
									  [NSArray arrayWithObjects:@"1247",@"S",@"Weekday",@"C",@"Evans",@"43",nil],
									  [NSArray arrayWithObjects:@"1250",@"S",@"Weekday",@"C",@"Englewood",@"43",nil],
									  [NSArray arrayWithObjects:@"1252",@"S",@"Weekday",@"C",@"Oxford",@"43",nil],
									  [NSArray arrayWithObjects:@"1256",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"43",nil],
									  [NSArray arrayWithObjects:@"1259",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"43",nil],
									  [NSArray arrayWithObjects:@"1261",@"S",@"Weekday",@"C",@"Union Station",@"44",nil],
									  [NSArray arrayWithObjects:@"1264",@"S",@"Weekday",@"C",@"Pepsi Center/Six Flags",@"44",nil],
									  [NSArray arrayWithObjects:@"1265",@"S",@"Weekday",@"C",@"Invesco Field at Mile High",@"44",nil],
									  [NSArray arrayWithObjects:@"1267",@"S",@"Weekday",@"C",@"Auraria West Campus",@"44",nil],
									  [NSArray arrayWithObjects:@"1270",@"S",@"Weekday",@"C",@"10th & Osage",@"44",nil],
									  [NSArray arrayWithObjects:@"1273",@"S",@"Weekday",@"C",@"Alameda",@"44",nil],
									  [NSArray arrayWithObjects:@"1274",@"S",@"Weekday",@"C",@"I-25/Broadway",@"44",nil],
									  [NSArray arrayWithObjects:@"1277",@"S",@"Weekday",@"C",@"Evans",@"44",nil],
									  [NSArray arrayWithObjects:@"1280",@"S",@"Weekday",@"C",@"Englewood",@"44",nil],
									  [NSArray arrayWithObjects:@"1282",@"S",@"Weekday",@"C",@"Oxford",@"44",nil],
									  [NSArray arrayWithObjects:@"1286",@"S",@"Weekday",@"C",@"Littleton/Downtown",@"44",nil],
									  [NSArray arrayWithObjects:@"1289",@"S",@"Weekday",@"C",@"Littleton/Mineral",@"44",nil],
									  
								   nil]];
	
	return returnArray;
}

@end
